// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBKajbIB925jT0U7UWEJdUntaUvZ6NlU',
    appId: '1:701947281078:web:c8a208ae5fb498114c7017',
    messagingSenderId: '701947281078',
    projectId: 'sawetapps',
    authDomain: 'sawetapps.firebaseapp.com',
    storageBucket: 'sawetapps.appspot.com',
    measurementId: 'G-HBMLS93NZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLeyd8vtgKnFB9xq6zpbe3R9jnBvYOb8k',
    appId: '1:701947281078:android:78b19a5e8483a53f4c7017',
    messagingSenderId: '701947281078',
    projectId: 'sawetapps',
    storageBucket: 'sawetapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmTAXyacNzRYfVom7IJWPDxxLwhHln3yk',
    appId: '1:701947281078:ios:5b55d2cdebae68734c7017',
    messagingSenderId: '701947281078',
    projectId: 'sawetapps',
    storageBucket: 'sawetapps.appspot.com',
    androidClientId: '701947281078-etgu5li6gq9tmrqvgh6ksuieikqf3pnl.apps.googleusercontent.com',
    iosClientId: '701947281078-5l2e1h1tpjj7j0akl0k247p7a73eav3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sawwet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmTAXyacNzRYfVom7IJWPDxxLwhHln3yk',
    appId: '1:701947281078:ios:5b55d2cdebae68734c7017',
    messagingSenderId: '701947281078',
    projectId: 'sawetapps',
    storageBucket: 'sawetapps.appspot.com',
    androidClientId: '701947281078-etgu5li6gq9tmrqvgh6ksuieikqf3pnl.apps.googleusercontent.com',
    iosClientId: '701947281078-5l2e1h1tpjj7j0akl0k247p7a73eav3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sawwet',
  );
}
